#+TITLE: negative-news-filter
#+AUTHOR: インターネットからストレスをなくす会
#+LANGUAGE: ja
#+OPTIONS: ^:nil num:nil

* インストール
- Firefox :: https://addons.mozilla.org/firefox/addon/negative-news-filter/
- Chromium :: [[https://github.com/mozilla/webextension-polyfill][MozillaのPolyfill]]を埋め込んで手動でインストールして下さい。

* 概要
- ニュースサイトでNGワードを含む記事リンクを非表示にするブラウザ拡張機能です。
  - ツールバーの♥アイコンから設定画面を開き、改行でワードを区切って追加して下さい。
  - 正規表現で記述します。
  - *「強引モード」* をオンにすることで、ルールの有無に関わらず全てのサイトでNGワードを含むaタグリンクを除去することができます。ただし、aタグに含まれない画像等の要素は除去できないのであくまでも簡易的なフィルタとしてお使い下さい。
  #+BEGIN_SRC
    炎上
    衝撃                                  // 基本的には単語を一語ずつ改行して記述
    感動|(一同)?驚愕|涙が(止|と)まらない  // パイプを使うと1行に複数語書ける
    G7|Ｇ７                               // 英数字は全角・半角両方書くと安全
    (本名|学歴|住所)は(\?|？)             // 正規表現なので、半角の?の前には\を忘れずに
  #+END_SRC
  - OKワードが含まれている記事は、NGワードが含まれていたとしても表示されます。書式はNGワードと同じです。
- NGワードに関わらず、以下のような迷惑要素も一括非表示にできます。
  - サイドバー :: ページ右側のサイドバー
  - ランキング :: 各種ランキング
  - 関連記事 :: *記事本文下* の関連記事・おすすめ記事
  - コメント :: コメント欄（素人・専門家不問）・コメント数・読者の反応（「いいね」など）
  - フッター :: ページ下側のフッター
  - 有料記事 :: 有料記事リンク。ただし、アイコンや値段表示を参照しているのでそれらがない記事には効果なし。

* 対応サイト
- [[./rules.json][rules.json]]でフィルタが定義されています。対応しているニュースサイトは以下の通りです（*印はスマホ版ページも対応）。
  - 新聞 :: 読売・日経・産経・朝日・毎日・北海道・河北・東京・下野・静岡・中日・京都・神戸・中国・高知・西日本（関連記事・ランキング未対応）
  - テレビ :: NHK・日テレ・FNN・テレ朝・TBS・カンテレ・ytv・ABC・MBS
  - ネットニュース（総合） :: Yahoo!・Google・ニコニコ・時事通信*・J-CAST・エキサイト・ライブドア・goo・BIGLOBE・47NEWS・iza・zakzak
  - 海外メディア（日本語） :: BBC・CNN・REUTERS・AFPBB
  - ビジネス・言論 :: アゴラ・JBpress・現代ビジネス・東洋経済・ダイヤモンド・プレジデント・フォーブス・ウェッジ・SAKISIRU
  - スポーツ・芸能 :: 報知・サンスポ・デイリー・東スポ・スポニチ・ゲンダイ・ABEMA
- Pull requestsやIssuesからリクエストを送って下されば適宜対応サイトを増やします！
- もちろん、アドオン内でユーザがマイルールを追加することも可能です。

* ルール（[[./rules.json][rules.json]]およびマイルール）の書き方
- JSON形式で記述します。キーは"url", "article", "paid", "side", "ranking", "related", "comment", "footer", "remove", "//"です。
  - "url" :: URLです。正規表現・行頭マッチ（^）で書きます。"\\"は"\\\\"と書くことに注意して下さい。
  - "article" :: NGワードで非表示にする対象の記事リンク要素です。CSSセレクタで指定し、値は配列形式で複数の要素を書くことができます（以下同様）。開発者向けモードではここで指定された要素がピンクで表示されます。
  - "paid" :: 有料記事を示す鍵アイコンや要素を指定します。"article"で指定されている要素の子孫ノードでないと効果が無いので注意です。
  - "side", "ranking", "related", "comment", "footer" :: それぞれサイドバー、ランキング、関連記事、コメント欄、フッターです。開発者向け設定ではここで指定された要素が赤い外枠で表示されます。なお、AutoPagerize系アドオンを使用している場合、footerの指定を間違えると不具合が生じることが多いので注意して下さい。
  - "remove" :: 本アドオンの動作に支障を来す要素（主にShadow DOMの親ノード）を指定します。設定の如何を問わず強制削除するので、極力使わないで下さい。
  - "//" :: 補足事項を書く欄です。"comment"キーはコメント欄要素ですので注意して下さい。
  #+BEGIN_SRC js
  [
    {                                         // JSON形式で
        "url": "^https?://example\\.com/",    // URLは正規表現・行頭マッチで。「\」は「\\」と書く
        "side": [                             // 配列の中に1つづつCSSセレクターで
            "div#side",
            ".sidebar"
        ],
        "ranking": ["div.ranking"],           // 1つならば配列でも
        "related": "div.related"              // 文字列でも良い
    },
    {
        "url": "^https?://example2\\.(com|jp)/",
        "footer": "footer",
        "article":[
            "div#main li",
            "ul.articleList > li"
        ],
        "paid": ["img.iconMember"],
        "//": "この中に補足事項を書いておく。commentキーはコメント欄要素に当てているので注意"
    }
  ]
  #+END_SRC

* 注意点
- GPLv3ライセンスに基づいています。
- *広告やCookie通知等の一般的な迷惑要素には対応しません。* このような要素については[[https://github.com/gorhill/uBlock][uBlock Origin]]の方が高度なブロックが出来るからです。そもそも、このアドオンはuBlock Originの補完目的として作成しました（NGワードの設定はuBOではやりにくく、また上記のような迷惑要素に対応しているフィルタが無かったため）。このような経緯であるため、本アドオンの利用者には別途uBlock Originをインストールした上で、AdGuard Japanese, AdGuard Annoyances, AdGuard Social Media, [[https://github.com/Yuki2718/adblock2][AdGuard Japanese filter Plus]]の計4種類のフィルタ（前3者はUBO標準組込、後1者はリンクから）を購読することを *強く推奨します。*
- Chromiumに正式に対応させる予定は当面ありません(MV3対応が面倒)。フォークはご自由にどうぞ。
